// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: video_events/events.proto

package video_events

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on WebsocketEvent with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *WebsocketEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WebsocketEvent with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in WebsocketEventMultiError,
// or nil if none found.
func (m *WebsocketEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *WebsocketEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch m.EventPayload.(type) {

	case *WebsocketEvent_HealthCheck:

		if all {
			switch v := interface{}(m.GetHealthCheck()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "HealthCheck",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "HealthCheck",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetHealthCheck()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WebsocketEventValidationError{
					field:  "HealthCheck",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WebsocketEvent_CallRinging:

		if all {
			switch v := interface{}(m.GetCallRinging()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "CallRinging",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "CallRinging",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetCallRinging()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WebsocketEventValidationError{
					field:  "CallRinging",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WebsocketEvent_CallCreated:

		if all {
			switch v := interface{}(m.GetCallCreated()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "CallCreated",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "CallCreated",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetCallCreated()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WebsocketEventValidationError{
					field:  "CallCreated",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WebsocketEvent_CallUpdated:

		if all {
			switch v := interface{}(m.GetCallUpdated()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "CallUpdated",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "CallUpdated",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetCallUpdated()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WebsocketEventValidationError{
					field:  "CallUpdated",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WebsocketEvent_CallEnded:

		if all {
			switch v := interface{}(m.GetCallEnded()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "CallEnded",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "CallEnded",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetCallEnded()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WebsocketEventValidationError{
					field:  "CallEnded",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WebsocketEvent_CallDeleted:

		if all {
			switch v := interface{}(m.GetCallDeleted()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "CallDeleted",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "CallDeleted",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetCallDeleted()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WebsocketEventValidationError{
					field:  "CallDeleted",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WebsocketEvent_UserUpdated:

		if all {
			switch v := interface{}(m.GetUserUpdated()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "UserUpdated",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "UserUpdated",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetUserUpdated()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WebsocketEventValidationError{
					field:  "UserUpdated",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WebsocketEvent_ParticipantInvited:

		if all {
			switch v := interface{}(m.GetParticipantInvited()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "ParticipantInvited",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "ParticipantInvited",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetParticipantInvited()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WebsocketEventValidationError{
					field:  "ParticipantInvited",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WebsocketEvent_ParticipantUpdated:

		if all {
			switch v := interface{}(m.GetParticipantUpdated()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "ParticipantUpdated",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "ParticipantUpdated",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetParticipantUpdated()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WebsocketEventValidationError{
					field:  "ParticipantUpdated",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WebsocketEvent_ParticipantDeleted:

		if all {
			switch v := interface{}(m.GetParticipantDeleted()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "ParticipantDeleted",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "ParticipantDeleted",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetParticipantDeleted()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WebsocketEventValidationError{
					field:  "ParticipantDeleted",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WebsocketEvent_ParticipantJoined:

		if all {
			switch v := interface{}(m.GetParticipantJoined()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "ParticipantJoined",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "ParticipantJoined",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetParticipantJoined()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WebsocketEventValidationError{
					field:  "ParticipantJoined",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WebsocketEvent_ParticipantLeft:

		if all {
			switch v := interface{}(m.GetParticipantLeft()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "ParticipantLeft",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "ParticipantLeft",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetParticipantLeft()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WebsocketEventValidationError{
					field:  "ParticipantLeft",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WebsocketEvent_BroadcastStarted:

		if all {
			switch v := interface{}(m.GetBroadcastStarted()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "BroadcastStarted",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "BroadcastStarted",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetBroadcastStarted()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WebsocketEventValidationError{
					field:  "BroadcastStarted",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WebsocketEvent_BroadcastEnded:

		if all {
			switch v := interface{}(m.GetBroadcastEnded()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "BroadcastEnded",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "BroadcastEnded",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetBroadcastEnded()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WebsocketEventValidationError{
					field:  "BroadcastEnded",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WebsocketEvent_AuthPayload:

		if all {
			switch v := interface{}(m.GetAuthPayload()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "AuthPayload",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "AuthPayload",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetAuthPayload()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WebsocketEventValidationError{
					field:  "AuthPayload",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WebsocketEvent_AudioMuted:

		if all {
			switch v := interface{}(m.GetAudioMuted()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "AudioMuted",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "AudioMuted",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetAudioMuted()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WebsocketEventValidationError{
					field:  "AudioMuted",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WebsocketEvent_AudioUnmuted:

		if all {
			switch v := interface{}(m.GetAudioUnmuted()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "AudioUnmuted",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "AudioUnmuted",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetAudioUnmuted()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WebsocketEventValidationError{
					field:  "AudioUnmuted",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WebsocketEvent_VideoStarted:

		if all {
			switch v := interface{}(m.GetVideoStarted()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "VideoStarted",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "VideoStarted",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetVideoStarted()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WebsocketEventValidationError{
					field:  "VideoStarted",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WebsocketEvent_VideoStopped:

		if all {
			switch v := interface{}(m.GetVideoStopped()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "VideoStopped",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "VideoStopped",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetVideoStopped()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WebsocketEventValidationError{
					field:  "VideoStopped",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WebsocketEvent_ScreenshareStarted:

		if all {
			switch v := interface{}(m.GetScreenshareStarted()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "ScreenshareStarted",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "ScreenshareStarted",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetScreenshareStarted()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WebsocketEventValidationError{
					field:  "ScreenshareStarted",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WebsocketEvent_ScreenshareStopped:

		if all {
			switch v := interface{}(m.GetScreenshareStopped()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "ScreenshareStopped",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "ScreenshareStopped",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetScreenshareStopped()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WebsocketEventValidationError{
					field:  "ScreenshareStopped",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WebsocketEvent_RecordingStarted:

		if all {
			switch v := interface{}(m.GetRecordingStarted()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "RecordingStarted",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "RecordingStarted",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetRecordingStarted()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WebsocketEventValidationError{
					field:  "RecordingStarted",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WebsocketEvent_RecordingStopped:

		if all {
			switch v := interface{}(m.GetRecordingStopped()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "RecordingStopped",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WebsocketEventValidationError{
						field:  "RecordingStopped",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetRecordingStopped()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WebsocketEventValidationError{
					field:  "RecordingStopped",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return WebsocketEventMultiError(errors)
	}

	return nil
}

// WebsocketEventMultiError is an error wrapping multiple validation errors
// returned by WebsocketEvent.ValidateAll() if the designated constraints
// aren't met.
type WebsocketEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WebsocketEventMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WebsocketEventMultiError) AllErrors() []error { return m }

// WebsocketEventValidationError is the validation error returned by
// WebsocketEvent.Validate if the designated constraints aren't met.
type WebsocketEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WebsocketEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WebsocketEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WebsocketEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WebsocketEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WebsocketEventValidationError) ErrorName() string { return "WebsocketEventValidationError" }

// Error satisfies the builtin error interface
func (e WebsocketEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWebsocketEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WebsocketEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WebsocketEventValidationError{}

// Validate checks the field values on Healthcheck with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Healthcheck) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Healthcheck with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in HealthcheckMultiError, or
// nil if none found.
func (m *Healthcheck) ValidateAll() error {
	return m.validate(true)
}

func (m *Healthcheck) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for ClientId

	// no validation rules for CallType

	// no validation rules for CallId

	// no validation rules for Video

	// no validation rules for Audio

	if len(errors) > 0 {
		return HealthcheckMultiError(errors)
	}

	return nil
}

// HealthcheckMultiError is an error wrapping multiple validation errors
// returned by Healthcheck.ValidateAll() if the designated constraints aren't met.
type HealthcheckMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HealthcheckMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HealthcheckMultiError) AllErrors() []error { return m }

// HealthcheckValidationError is the validation error returned by
// Healthcheck.Validate if the designated constraints aren't met.
type HealthcheckValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HealthcheckValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HealthcheckValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HealthcheckValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HealthcheckValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HealthcheckValidationError) ErrorName() string { return "HealthcheckValidationError" }

// Error satisfies the builtin error interface
func (e HealthcheckValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHealthcheck.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HealthcheckValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HealthcheckValidationError{}

// Validate checks the field values on AuthPayload with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AuthPayload) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthPayload with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AuthPayloadMultiError, or
// nil if none found.
func (m *AuthPayload) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthPayload) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetUser()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AuthPayloadValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AuthPayloadValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUser()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AuthPayloadValidationError{
				field:  "User",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetDevice()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AuthPayloadValidationError{
					field:  "Device",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AuthPayloadValidationError{
					field:  "Device",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDevice()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AuthPayloadValidationError{
				field:  "Device",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for ApiKey

	// no validation rules for Token

	if len(errors) > 0 {
		return AuthPayloadMultiError(errors)
	}

	return nil
}

// AuthPayloadMultiError is an error wrapping multiple validation errors
// returned by AuthPayload.ValidateAll() if the designated constraints aren't met.
type AuthPayloadMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthPayloadMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthPayloadMultiError) AllErrors() []error { return m }

// AuthPayloadValidationError is the validation error returned by
// AuthPayload.Validate if the designated constraints aren't met.
type AuthPayloadValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthPayloadValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthPayloadValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthPayloadValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthPayloadValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthPayloadValidationError) ErrorName() string { return "AuthPayloadValidationError" }

// Error satisfies the builtin error interface
func (e AuthPayloadValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthPayload.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthPayloadValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthPayloadValidationError{}

// Validate checks the field values on CallRinging with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CallRinging) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CallRinging with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CallRingingMultiError, or
// nil if none found.
func (m *CallRinging) ValidateAll() error {
	return m.validate(true)
}

func (m *CallRinging) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCall()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CallRingingValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CallRingingValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCall()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CallRingingValidationError{
				field:  "Call",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CallRingingMultiError(errors)
	}

	return nil
}

// CallRingingMultiError is an error wrapping multiple validation errors
// returned by CallRinging.ValidateAll() if the designated constraints aren't met.
type CallRingingMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CallRingingMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CallRingingMultiError) AllErrors() []error { return m }

// CallRingingValidationError is the validation error returned by
// CallRinging.Validate if the designated constraints aren't met.
type CallRingingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CallRingingValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CallRingingValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CallRingingValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CallRingingValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CallRingingValidationError) ErrorName() string { return "CallRingingValidationError" }

// Error satisfies the builtin error interface
func (e CallRingingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCallRinging.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CallRingingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CallRingingValidationError{}

// Validate checks the field values on CallCreated with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CallCreated) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CallCreated with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CallCreatedMultiError, or
// nil if none found.
func (m *CallCreated) ValidateAll() error {
	return m.validate(true)
}

func (m *CallCreated) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCall()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CallCreatedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CallCreatedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCall()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CallCreatedValidationError{
				field:  "Call",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CallCreatedMultiError(errors)
	}

	return nil
}

// CallCreatedMultiError is an error wrapping multiple validation errors
// returned by CallCreated.ValidateAll() if the designated constraints aren't met.
type CallCreatedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CallCreatedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CallCreatedMultiError) AllErrors() []error { return m }

// CallCreatedValidationError is the validation error returned by
// CallCreated.Validate if the designated constraints aren't met.
type CallCreatedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CallCreatedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CallCreatedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CallCreatedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CallCreatedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CallCreatedValidationError) ErrorName() string { return "CallCreatedValidationError" }

// Error satisfies the builtin error interface
func (e CallCreatedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCallCreated.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CallCreatedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CallCreatedValidationError{}

// Validate checks the field values on CallUpdated with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CallUpdated) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CallUpdated with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CallUpdatedMultiError, or
// nil if none found.
func (m *CallUpdated) ValidateAll() error {
	return m.validate(true)
}

func (m *CallUpdated) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCall()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CallUpdatedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CallUpdatedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCall()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CallUpdatedValidationError{
				field:  "Call",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CallUpdatedMultiError(errors)
	}

	return nil
}

// CallUpdatedMultiError is an error wrapping multiple validation errors
// returned by CallUpdated.ValidateAll() if the designated constraints aren't met.
type CallUpdatedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CallUpdatedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CallUpdatedMultiError) AllErrors() []error { return m }

// CallUpdatedValidationError is the validation error returned by
// CallUpdated.Validate if the designated constraints aren't met.
type CallUpdatedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CallUpdatedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CallUpdatedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CallUpdatedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CallUpdatedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CallUpdatedValidationError) ErrorName() string { return "CallUpdatedValidationError" }

// Error satisfies the builtin error interface
func (e CallUpdatedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCallUpdated.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CallUpdatedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CallUpdatedValidationError{}

// Validate checks the field values on CallEnded with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CallEnded) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CallEnded with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CallEndedMultiError, or nil
// if none found.
func (m *CallEnded) ValidateAll() error {
	return m.validate(true)
}

func (m *CallEnded) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCall()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CallEndedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CallEndedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCall()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CallEndedValidationError{
				field:  "Call",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CallEndedMultiError(errors)
	}

	return nil
}

// CallEndedMultiError is an error wrapping multiple validation errors returned
// by CallEnded.ValidateAll() if the designated constraints aren't met.
type CallEndedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CallEndedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CallEndedMultiError) AllErrors() []error { return m }

// CallEndedValidationError is the validation error returned by
// CallEnded.Validate if the designated constraints aren't met.
type CallEndedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CallEndedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CallEndedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CallEndedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CallEndedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CallEndedValidationError) ErrorName() string { return "CallEndedValidationError" }

// Error satisfies the builtin error interface
func (e CallEndedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCallEnded.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CallEndedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CallEndedValidationError{}

// Validate checks the field values on CallDeleted with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CallDeleted) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CallDeleted with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CallDeletedMultiError, or
// nil if none found.
func (m *CallDeleted) ValidateAll() error {
	return m.validate(true)
}

func (m *CallDeleted) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCall()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CallDeletedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CallDeletedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCall()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CallDeletedValidationError{
				field:  "Call",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CallDeletedMultiError(errors)
	}

	return nil
}

// CallDeletedMultiError is an error wrapping multiple validation errors
// returned by CallDeleted.ValidateAll() if the designated constraints aren't met.
type CallDeletedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CallDeletedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CallDeletedMultiError) AllErrors() []error { return m }

// CallDeletedValidationError is the validation error returned by
// CallDeleted.Validate if the designated constraints aren't met.
type CallDeletedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CallDeletedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CallDeletedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CallDeletedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CallDeletedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CallDeletedValidationError) ErrorName() string { return "CallDeletedValidationError" }

// Error satisfies the builtin error interface
func (e CallDeletedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCallDeleted.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CallDeletedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CallDeletedValidationError{}

// Validate checks the field values on AudioMuted with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AudioMuted) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AudioMuted with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AudioMutedMultiError, or
// nil if none found.
func (m *AudioMuted) ValidateAll() error {
	return m.validate(true)
}

func (m *AudioMuted) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCall()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AudioMutedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AudioMutedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCall()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AudioMutedValidationError{
				field:  "Call",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	switch m.Target.(type) {

	case *AudioMuted_UserId:
		// no validation rules for UserId

	case *AudioMuted_AllUsers:
		// no validation rules for AllUsers

	}

	if len(errors) > 0 {
		return AudioMutedMultiError(errors)
	}

	return nil
}

// AudioMutedMultiError is an error wrapping multiple validation errors
// returned by AudioMuted.ValidateAll() if the designated constraints aren't met.
type AudioMutedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AudioMutedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AudioMutedMultiError) AllErrors() []error { return m }

// AudioMutedValidationError is the validation error returned by
// AudioMuted.Validate if the designated constraints aren't met.
type AudioMutedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AudioMutedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AudioMutedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AudioMutedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AudioMutedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AudioMutedValidationError) ErrorName() string { return "AudioMutedValidationError" }

// Error satisfies the builtin error interface
func (e AudioMutedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAudioMuted.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AudioMutedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AudioMutedValidationError{}

// Validate checks the field values on AudioUnmuted with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AudioUnmuted) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AudioUnmuted with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AudioUnmutedMultiError, or
// nil if none found.
func (m *AudioUnmuted) ValidateAll() error {
	return m.validate(true)
}

func (m *AudioUnmuted) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCall()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AudioUnmutedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AudioUnmutedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCall()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AudioUnmutedValidationError{
				field:  "Call",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for UserId

	if len(errors) > 0 {
		return AudioUnmutedMultiError(errors)
	}

	return nil
}

// AudioUnmutedMultiError is an error wrapping multiple validation errors
// returned by AudioUnmuted.ValidateAll() if the designated constraints aren't met.
type AudioUnmutedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AudioUnmutedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AudioUnmutedMultiError) AllErrors() []error { return m }

// AudioUnmutedValidationError is the validation error returned by
// AudioUnmuted.Validate if the designated constraints aren't met.
type AudioUnmutedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AudioUnmutedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AudioUnmutedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AudioUnmutedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AudioUnmutedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AudioUnmutedValidationError) ErrorName() string { return "AudioUnmutedValidationError" }

// Error satisfies the builtin error interface
func (e AudioUnmutedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAudioUnmuted.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AudioUnmutedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AudioUnmutedValidationError{}

// Validate checks the field values on VideoStarted with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *VideoStarted) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VideoStarted with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in VideoStartedMultiError, or
// nil if none found.
func (m *VideoStarted) ValidateAll() error {
	return m.validate(true)
}

func (m *VideoStarted) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCall()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VideoStartedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VideoStartedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCall()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VideoStartedValidationError{
				field:  "Call",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for UserId

	if len(errors) > 0 {
		return VideoStartedMultiError(errors)
	}

	return nil
}

// VideoStartedMultiError is an error wrapping multiple validation errors
// returned by VideoStarted.ValidateAll() if the designated constraints aren't met.
type VideoStartedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VideoStartedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VideoStartedMultiError) AllErrors() []error { return m }

// VideoStartedValidationError is the validation error returned by
// VideoStarted.Validate if the designated constraints aren't met.
type VideoStartedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VideoStartedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VideoStartedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VideoStartedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VideoStartedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VideoStartedValidationError) ErrorName() string { return "VideoStartedValidationError" }

// Error satisfies the builtin error interface
func (e VideoStartedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVideoStarted.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VideoStartedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VideoStartedValidationError{}

// Validate checks the field values on VideoStopped with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *VideoStopped) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VideoStopped with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in VideoStoppedMultiError, or
// nil if none found.
func (m *VideoStopped) ValidateAll() error {
	return m.validate(true)
}

func (m *VideoStopped) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCall()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VideoStoppedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VideoStoppedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCall()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VideoStoppedValidationError{
				field:  "Call",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for UserId

	if len(errors) > 0 {
		return VideoStoppedMultiError(errors)
	}

	return nil
}

// VideoStoppedMultiError is an error wrapping multiple validation errors
// returned by VideoStopped.ValidateAll() if the designated constraints aren't met.
type VideoStoppedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VideoStoppedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VideoStoppedMultiError) AllErrors() []error { return m }

// VideoStoppedValidationError is the validation error returned by
// VideoStopped.Validate if the designated constraints aren't met.
type VideoStoppedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VideoStoppedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VideoStoppedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VideoStoppedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VideoStoppedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VideoStoppedValidationError) ErrorName() string { return "VideoStoppedValidationError" }

// Error satisfies the builtin error interface
func (e VideoStoppedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVideoStopped.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VideoStoppedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VideoStoppedValidationError{}

// Validate checks the field values on ScreenshareStarted with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ScreenshareStarted) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ScreenshareStarted with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ScreenshareStartedMultiError, or nil if none found.
func (m *ScreenshareStarted) ValidateAll() error {
	return m.validate(true)
}

func (m *ScreenshareStarted) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCall()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ScreenshareStartedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ScreenshareStartedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCall()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ScreenshareStartedValidationError{
				field:  "Call",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for UserId

	if len(errors) > 0 {
		return ScreenshareStartedMultiError(errors)
	}

	return nil
}

// ScreenshareStartedMultiError is an error wrapping multiple validation errors
// returned by ScreenshareStarted.ValidateAll() if the designated constraints
// aren't met.
type ScreenshareStartedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ScreenshareStartedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ScreenshareStartedMultiError) AllErrors() []error { return m }

// ScreenshareStartedValidationError is the validation error returned by
// ScreenshareStarted.Validate if the designated constraints aren't met.
type ScreenshareStartedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ScreenshareStartedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ScreenshareStartedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ScreenshareStartedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ScreenshareStartedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ScreenshareStartedValidationError) ErrorName() string {
	return "ScreenshareStartedValidationError"
}

// Error satisfies the builtin error interface
func (e ScreenshareStartedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sScreenshareStarted.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ScreenshareStartedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ScreenshareStartedValidationError{}

// Validate checks the field values on ScreenshareStopped with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ScreenshareStopped) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ScreenshareStopped with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ScreenshareStoppedMultiError, or nil if none found.
func (m *ScreenshareStopped) ValidateAll() error {
	return m.validate(true)
}

func (m *ScreenshareStopped) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCall()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ScreenshareStoppedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ScreenshareStoppedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCall()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ScreenshareStoppedValidationError{
				field:  "Call",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for UserId

	if len(errors) > 0 {
		return ScreenshareStoppedMultiError(errors)
	}

	return nil
}

// ScreenshareStoppedMultiError is an error wrapping multiple validation errors
// returned by ScreenshareStopped.ValidateAll() if the designated constraints
// aren't met.
type ScreenshareStoppedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ScreenshareStoppedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ScreenshareStoppedMultiError) AllErrors() []error { return m }

// ScreenshareStoppedValidationError is the validation error returned by
// ScreenshareStopped.Validate if the designated constraints aren't met.
type ScreenshareStoppedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ScreenshareStoppedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ScreenshareStoppedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ScreenshareStoppedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ScreenshareStoppedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ScreenshareStoppedValidationError) ErrorName() string {
	return "ScreenshareStoppedValidationError"
}

// Error satisfies the builtin error interface
func (e ScreenshareStoppedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sScreenshareStopped.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ScreenshareStoppedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ScreenshareStoppedValidationError{}

// Validate checks the field values on RecordingStarted with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RecordingStarted) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RecordingStarted with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RecordingStartedMultiError, or nil if none found.
func (m *RecordingStarted) ValidateAll() error {
	return m.validate(true)
}

func (m *RecordingStarted) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCall()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RecordingStartedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RecordingStartedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCall()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RecordingStartedValidationError{
				field:  "Call",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RecordingStartedMultiError(errors)
	}

	return nil
}

// RecordingStartedMultiError is an error wrapping multiple validation errors
// returned by RecordingStarted.ValidateAll() if the designated constraints
// aren't met.
type RecordingStartedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RecordingStartedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RecordingStartedMultiError) AllErrors() []error { return m }

// RecordingStartedValidationError is the validation error returned by
// RecordingStarted.Validate if the designated constraints aren't met.
type RecordingStartedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RecordingStartedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RecordingStartedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RecordingStartedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RecordingStartedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RecordingStartedValidationError) ErrorName() string { return "RecordingStartedValidationError" }

// Error satisfies the builtin error interface
func (e RecordingStartedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRecordingStarted.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RecordingStartedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RecordingStartedValidationError{}

// Validate checks the field values on RecordingStopped with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RecordingStopped) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RecordingStopped with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RecordingStoppedMultiError, or nil if none found.
func (m *RecordingStopped) ValidateAll() error {
	return m.validate(true)
}

func (m *RecordingStopped) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCall()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RecordingStoppedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RecordingStoppedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCall()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RecordingStoppedValidationError{
				field:  "Call",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RecordingStoppedMultiError(errors)
	}

	return nil
}

// RecordingStoppedMultiError is an error wrapping multiple validation errors
// returned by RecordingStopped.ValidateAll() if the designated constraints
// aren't met.
type RecordingStoppedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RecordingStoppedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RecordingStoppedMultiError) AllErrors() []error { return m }

// RecordingStoppedValidationError is the validation error returned by
// RecordingStopped.Validate if the designated constraints aren't met.
type RecordingStoppedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RecordingStoppedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RecordingStoppedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RecordingStoppedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RecordingStoppedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RecordingStoppedValidationError) ErrorName() string { return "RecordingStoppedValidationError" }

// Error satisfies the builtin error interface
func (e RecordingStoppedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRecordingStopped.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RecordingStoppedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RecordingStoppedValidationError{}

// Validate checks the field values on UserUpdated with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserUpdated) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserUpdated with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserUpdatedMultiError, or
// nil if none found.
func (m *UserUpdated) ValidateAll() error {
	return m.validate(true)
}

func (m *UserUpdated) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetUser()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserUpdatedValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserUpdatedValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUser()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserUpdatedValidationError{
				field:  "User",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UserUpdatedMultiError(errors)
	}

	return nil
}

// UserUpdatedMultiError is an error wrapping multiple validation errors
// returned by UserUpdated.ValidateAll() if the designated constraints aren't met.
type UserUpdatedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserUpdatedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserUpdatedMultiError) AllErrors() []error { return m }

// UserUpdatedValidationError is the validation error returned by
// UserUpdated.Validate if the designated constraints aren't met.
type UserUpdatedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserUpdatedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserUpdatedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserUpdatedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserUpdatedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserUpdatedValidationError) ErrorName() string { return "UserUpdatedValidationError" }

// Error satisfies the builtin error interface
func (e UserUpdatedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserUpdated.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserUpdatedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserUpdatedValidationError{}

// Validate checks the field values on ParticipantInvited with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ParticipantInvited) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ParticipantInvited with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ParticipantInvitedMultiError, or nil if none found.
func (m *ParticipantInvited) ValidateAll() error {
	return m.validate(true)
}

func (m *ParticipantInvited) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCall()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ParticipantInvitedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ParticipantInvitedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCall()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ParticipantInvitedValidationError{
				field:  "Call",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetParticipant()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ParticipantInvitedValidationError{
					field:  "Participant",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ParticipantInvitedValidationError{
					field:  "Participant",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetParticipant()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ParticipantInvitedValidationError{
				field:  "Participant",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ParticipantInvitedMultiError(errors)
	}

	return nil
}

// ParticipantInvitedMultiError is an error wrapping multiple validation errors
// returned by ParticipantInvited.ValidateAll() if the designated constraints
// aren't met.
type ParticipantInvitedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ParticipantInvitedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ParticipantInvitedMultiError) AllErrors() []error { return m }

// ParticipantInvitedValidationError is the validation error returned by
// ParticipantInvited.Validate if the designated constraints aren't met.
type ParticipantInvitedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ParticipantInvitedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ParticipantInvitedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ParticipantInvitedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ParticipantInvitedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ParticipantInvitedValidationError) ErrorName() string {
	return "ParticipantInvitedValidationError"
}

// Error satisfies the builtin error interface
func (e ParticipantInvitedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sParticipantInvited.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ParticipantInvitedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ParticipantInvitedValidationError{}

// Validate checks the field values on ParticipantUpdated with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ParticipantUpdated) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ParticipantUpdated with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ParticipantUpdatedMultiError, or nil if none found.
func (m *ParticipantUpdated) ValidateAll() error {
	return m.validate(true)
}

func (m *ParticipantUpdated) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCall()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ParticipantUpdatedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ParticipantUpdatedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCall()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ParticipantUpdatedValidationError{
				field:  "Call",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetParticipant()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ParticipantUpdatedValidationError{
					field:  "Participant",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ParticipantUpdatedValidationError{
					field:  "Participant",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetParticipant()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ParticipantUpdatedValidationError{
				field:  "Participant",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ParticipantUpdatedMultiError(errors)
	}

	return nil
}

// ParticipantUpdatedMultiError is an error wrapping multiple validation errors
// returned by ParticipantUpdated.ValidateAll() if the designated constraints
// aren't met.
type ParticipantUpdatedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ParticipantUpdatedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ParticipantUpdatedMultiError) AllErrors() []error { return m }

// ParticipantUpdatedValidationError is the validation error returned by
// ParticipantUpdated.Validate if the designated constraints aren't met.
type ParticipantUpdatedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ParticipantUpdatedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ParticipantUpdatedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ParticipantUpdatedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ParticipantUpdatedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ParticipantUpdatedValidationError) ErrorName() string {
	return "ParticipantUpdatedValidationError"
}

// Error satisfies the builtin error interface
func (e ParticipantUpdatedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sParticipantUpdated.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ParticipantUpdatedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ParticipantUpdatedValidationError{}

// Validate checks the field values on ParticipantDeleted with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ParticipantDeleted) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ParticipantDeleted with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ParticipantDeletedMultiError, or nil if none found.
func (m *ParticipantDeleted) ValidateAll() error {
	return m.validate(true)
}

func (m *ParticipantDeleted) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCall()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ParticipantDeletedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ParticipantDeletedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCall()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ParticipantDeletedValidationError{
				field:  "Call",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for UserId

	if len(errors) > 0 {
		return ParticipantDeletedMultiError(errors)
	}

	return nil
}

// ParticipantDeletedMultiError is an error wrapping multiple validation errors
// returned by ParticipantDeleted.ValidateAll() if the designated constraints
// aren't met.
type ParticipantDeletedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ParticipantDeletedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ParticipantDeletedMultiError) AllErrors() []error { return m }

// ParticipantDeletedValidationError is the validation error returned by
// ParticipantDeleted.Validate if the designated constraints aren't met.
type ParticipantDeletedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ParticipantDeletedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ParticipantDeletedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ParticipantDeletedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ParticipantDeletedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ParticipantDeletedValidationError) ErrorName() string {
	return "ParticipantDeletedValidationError"
}

// Error satisfies the builtin error interface
func (e ParticipantDeletedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sParticipantDeleted.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ParticipantDeletedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ParticipantDeletedValidationError{}

// Validate checks the field values on ParticipantJoined with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ParticipantJoined) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ParticipantJoined with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ParticipantJoinedMultiError, or nil if none found.
func (m *ParticipantJoined) ValidateAll() error {
	return m.validate(true)
}

func (m *ParticipantJoined) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCall()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ParticipantJoinedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ParticipantJoinedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCall()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ParticipantJoinedValidationError{
				field:  "Call",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetParticipant()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ParticipantJoinedValidationError{
					field:  "Participant",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ParticipantJoinedValidationError{
					field:  "Participant",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetParticipant()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ParticipantJoinedValidationError{
				field:  "Participant",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ParticipantJoinedMultiError(errors)
	}

	return nil
}

// ParticipantJoinedMultiError is an error wrapping multiple validation errors
// returned by ParticipantJoined.ValidateAll() if the designated constraints
// aren't met.
type ParticipantJoinedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ParticipantJoinedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ParticipantJoinedMultiError) AllErrors() []error { return m }

// ParticipantJoinedValidationError is the validation error returned by
// ParticipantJoined.Validate if the designated constraints aren't met.
type ParticipantJoinedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ParticipantJoinedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ParticipantJoinedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ParticipantJoinedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ParticipantJoinedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ParticipantJoinedValidationError) ErrorName() string {
	return "ParticipantJoinedValidationError"
}

// Error satisfies the builtin error interface
func (e ParticipantJoinedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sParticipantJoined.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ParticipantJoinedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ParticipantJoinedValidationError{}

// Validate checks the field values on ParticipantLeft with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ParticipantLeft) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ParticipantLeft with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ParticipantLeftMultiError, or nil if none found.
func (m *ParticipantLeft) ValidateAll() error {
	return m.validate(true)
}

func (m *ParticipantLeft) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCall()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ParticipantLeftValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ParticipantLeftValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCall()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ParticipantLeftValidationError{
				field:  "Call",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetParticipant()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ParticipantLeftValidationError{
					field:  "Participant",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ParticipantLeftValidationError{
					field:  "Participant",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetParticipant()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ParticipantLeftValidationError{
				field:  "Participant",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ParticipantLeftMultiError(errors)
	}

	return nil
}

// ParticipantLeftMultiError is an error wrapping multiple validation errors
// returned by ParticipantLeft.ValidateAll() if the designated constraints
// aren't met.
type ParticipantLeftMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ParticipantLeftMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ParticipantLeftMultiError) AllErrors() []error { return m }

// ParticipantLeftValidationError is the validation error returned by
// ParticipantLeft.Validate if the designated constraints aren't met.
type ParticipantLeftValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ParticipantLeftValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ParticipantLeftValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ParticipantLeftValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ParticipantLeftValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ParticipantLeftValidationError) ErrorName() string { return "ParticipantLeftValidationError" }

// Error satisfies the builtin error interface
func (e ParticipantLeftValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sParticipantLeft.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ParticipantLeftValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ParticipantLeftValidationError{}

// Validate checks the field values on BroadcastStarted with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *BroadcastStarted) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BroadcastStarted with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BroadcastStartedMultiError, or nil if none found.
func (m *BroadcastStarted) ValidateAll() error {
	return m.validate(true)
}

func (m *BroadcastStarted) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCall()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BroadcastStartedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BroadcastStartedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCall()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BroadcastStartedValidationError{
				field:  "Call",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return BroadcastStartedMultiError(errors)
	}

	return nil
}

// BroadcastStartedMultiError is an error wrapping multiple validation errors
// returned by BroadcastStarted.ValidateAll() if the designated constraints
// aren't met.
type BroadcastStartedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BroadcastStartedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BroadcastStartedMultiError) AllErrors() []error { return m }

// BroadcastStartedValidationError is the validation error returned by
// BroadcastStarted.Validate if the designated constraints aren't met.
type BroadcastStartedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BroadcastStartedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BroadcastStartedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BroadcastStartedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BroadcastStartedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BroadcastStartedValidationError) ErrorName() string { return "BroadcastStartedValidationError" }

// Error satisfies the builtin error interface
func (e BroadcastStartedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBroadcastStarted.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BroadcastStartedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BroadcastStartedValidationError{}

// Validate checks the field values on BroadcastEnded with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BroadcastEnded) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BroadcastEnded with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BroadcastEndedMultiError,
// or nil if none found.
func (m *BroadcastEnded) ValidateAll() error {
	return m.validate(true)
}

func (m *BroadcastEnded) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCall()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BroadcastEndedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BroadcastEndedValidationError{
					field:  "Call",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCall()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BroadcastEndedValidationError{
				field:  "Call",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return BroadcastEndedMultiError(errors)
	}

	return nil
}

// BroadcastEndedMultiError is an error wrapping multiple validation errors
// returned by BroadcastEnded.ValidateAll() if the designated constraints
// aren't met.
type BroadcastEndedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BroadcastEndedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BroadcastEndedMultiError) AllErrors() []error { return m }

// BroadcastEndedValidationError is the validation error returned by
// BroadcastEnded.Validate if the designated constraints aren't met.
type BroadcastEndedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BroadcastEndedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BroadcastEndedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BroadcastEndedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BroadcastEndedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BroadcastEndedValidationError) ErrorName() string { return "BroadcastEndedValidationError" }

// Error satisfies the builtin error interface
func (e BroadcastEndedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBroadcastEnded.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BroadcastEndedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BroadcastEndedValidationError{}
